nlpserv:
  container_name: nlps
  image: plandes/nlpservice:0.0.3
  ports:
    - "9100:9100"
  environment:
    COMPONENTS: tokenize,sentence,stopword,part-of-speech,morphology,named-entity-recognizer,parse-tree,coreference,semantic-role-labeler
