nlpserv:
  container_name: nlps
  image: plandes/nlpservice:snapshot
  ports:
    - "9100:9100"
  environment:
    COMPONENTS: tokenize,sentence,part-of-speech,morphology,stopword,named-entity-recognizer,parse-tree,natural-logic,sentiment,coreference,semantic-role-labeler
