nlpserv:
  container_name: nlps
  image: plandes/nlpservice:0.0.7
  ports:
    - "9100:9100"
  environment:
    COMPONENTS: tokenize,sentence,part-of-speech,morphology,stopword,named-entity-recognizer,parse-tree,sentiment,coreference,semantic-role-labeler
