# tweet taken from https://github.com/dushyant89/SentimentAnalysis
POST http://localhost:9100/parse
Content-Type: application/x-www-form-urlencoded
utterance=Beginning JavaScript and CSS Development with jQuery #javascript #css #jquery http://bit.ly/TO3e5
